#!/usr/bin/python3
# Usage ./stop-all qdag_instalation_folder

import sys, os

folder = sys.argv[1]
workersfile = "workers"
masterFile = "master"
ssh_key = os.path.expanduser("~/.ssh/pqdag")
ssh_opts = "-i %s -o StrictHostKeyChecking=no" % ssh_key

master = open(masterFile,'r').readlines()[0].strip()
os.system("ssh %s %s 'python3 %s/stop-master %s'" %(ssh_opts, master,folder,folder))

workers = open(workersfile,'r').readlines()
for i in workers:
   node = i.strip()
   os.system("ssh %s %s 'python3 %s/stop-worker %s'" %(ssh_opts, node,folder,folder))

print("Workers and Master Stopped !")